"""init_migrations

Revision ID: 386757b96e4c
Revises: 
Create Date: 2025-01-09 16:04:41.909142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '386757b96e4c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_board_tiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_data_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('flag_color', sa.String(), nullable=False),
    sa.Column('seen', sa.Boolean(), nullable=False),
    sa.Column('x_axis', sa.Integer(), nullable=False),
    sa.Column('y_axis', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_score', sa.Integer(), nullable=False),
    sa.Column('opponent_score', sa.Integer(), nullable=False),
    sa.Column('timer', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('host_color', sa.String(), nullable=False),
    sa.Column('opponent_color', sa.String(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('games')
    op.drop_table('game_data')
    op.drop_table('game_board_tiles')
    # ### end Alembic commands ###
